serverAddr = "__SERVERADDR__"
serverPort = __SERVERPORT__
transport.protocol = "quic"

auth.method = "__AUTHMETHOD__"
__AUTHTOKEN_LINE__

tlsEnable = __TLSENABLE__
__TLSCERT_LINE__
__TLSKEY_LINE__
__TLSCA_LINE__

auth.token = "__AUTHTOKEN__"
log.to = "/share/frpc.log"
log.level = "info"
log.maxDays = 3
