[[proxies]]
name = "__NAME__"
type = "__TYPE__"
localIP = "__LOCALIP__"
localPort = __LOCALPORT__
__REMOTEPORT_LINE__
__SUBDOMAIN_LINE__
__CUSTOMDOMAINS_LINE__
transport.useEncryption = __USEENCRYPTION__
transport.useCompression = __USECOMPRESSION__
