[[proxies]]
name = "__NAME__"
type = "__TYPE__"
localIP = "__LOCALIP__"
localPort = __LOCALPORT__
remotePort = __REMOTEPORT__
customDomains = [__CUSTOMDOMAINS__]
transport.useEncryption = __USEENCRYPTION__
transport.useCompression = __USECOMPRESSION__
