name: "FRP Client"
version: "1.0.6"
slug: ha_frpc

description: >-
  Securely expose your Home Assistant over the internet via FRP (Fast Reverse Proxy).

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

host_network: true
startup: application
boot: auto
init: false

map:
  - type: share
    read_only: false
  - type: ssl
    read_only: true

privileged:
  - NET_ADMIN

devices:
  - /dev/net/tun

options:
  serverAddr: "your-vps.example.com"
  serverPort: 7000
  authMethod: "token"        # or "insecure"
  authToken: "secret-token"
  tlsEnable: true
  tlsCertFile: "/ssl/fullchain.pem"
  tlsKeyFile: "/ssl/privkey.pem"
  tlsCaFile: "/ssl/fullchain.pem"
  proxies:
    - name: "homeassistant"
      type: "http"
      localIP: "127.0.0.1"
      localPort: 8123
      remotePort: 8123
      subdomain: "home"
      customDomains:
        - "home.silkslime.ru"
      useEncryption: true
      useCompression: true

schema:
  serverAddr: str
  serverPort: int
  authMethod: match(insecure|token)
  authToken: password
  tlsEnable: bool
  tlsCertFile: str
  tlsKeyFile: str
  tlsCaFile: str
  proxies:
    - name: str
      type: match(http|https|tcp|udp)
      localIP: str
      localPort: port
      remotePort: port
      subdomain: str
      customDomains:
        - str
      useEncryption: bool
      useCompression: bool
